### ISSUE TITLE
Zurück ins Boot!

### ISSUE THREAD

**Issue by L2P-Academy** [L2P-Academy/FIAE1_RPG#14]
Wir wollen niemanden zurücklassen! An alle Teilnehmer, die noch nicht dabei sind, bietet sich hier die Möglichkeit wieder richtig einzusteigen.

**Comment by antcedric91** [comment]
*schwimmt mit den Fischen*

**Comment by L2P-Academy** [comment]
![grafik](https://github.com/L2P-Academy/FIAE1_DnD/assets/161337219/a73cec56-5838-4abf-bebd-86633adbb107)
