### ISSUE TITLE
Dokumentation/Wiki

### ISSUE THREAD

**Issue by L2P-Academy** [L2P-Academy/FIAE1_RPG#146]
Es muss für alles ein Wiki erstellt werden + Überprüfung der Code-Kommentare, ggf. Refactoring
-> In das Wiki sollen Code-Conventions eingepflegt werden

**Comment by L2P-Academy** [comment]
Gliederung für Wiki:

1. Einführung
2. Codeconvention
3. Klassenstruktur
4. Datenbank (Tabellen + Spalten + Beziehungen)
5. Anforderungen
6. Ressourcen
7. Schnittstellen / Bibliotheken / Plugins
8. Programmablauf (Grafik / Zustandsdiagramm)
9. Tutorial
10. Testdokumentation
11. Lizenz (Nutzung/Verbreitung etc)
12. EULA
13. Quellenangaben
14. Special Thanks
15. AI-Generated Content

**Comment by L2P-Academy** [comment]
Codeconvention mache ich

**Comment by christian-gassmann** [comment]
Datenbank mache ich

**Comment by Rakinos89** [comment]
Klassenstruktur und Programmablauf (Grafik / Zustandsdiagramm) mache ich

**Comment by weirdmustard** [comment]
Joa, dann mach ich heut Nachmittag noch die Ressourcen-Seite

**Comment by weirdmustard** [comment]
Aktuell noch zu tun:

[2. Codeconvention]
[3. Klassenstruktur]
[5. Spielmechaniken]
[7. Schnittstellen / Bibliotheken / Plugins]
[10. Testdokumentation]
[8. Programmablauf]

**Comment by weirdmustard** [comment]
Aktuell noch leere Wiki-Seiten:

3. Klassenstruktur
4. Spielmechaniken
7. Schnittstellen, Bibliotheken & Plugins
8. Programmablauf & Testdokumentation

@Rakinos89 Du wolltest die Programmabläufe auch als Diagramm darstellen, das kommt jetzt mit bei 8. rein, L2P meinte, das ist alles Testdokumentation
