### ISSUE TITLE
SettingsView, was soll rein? + Updates und aktueller Stand

### ISSUE THREAD

**Issue by Pandaoria** [L2P-Academy/FIAE1_RPG#161]
Hallo an alle. Ich möchte mich diese Woche an die Settings machen. Jetzt wollte ich einfach mal dass jeder sagen kann was er als Sinnvoll erachtet (und auch machbar). Hier sind schon mal die Einstellungen die ich denke die man einbauen kann:

- Lautstärke
- Vollbild an/aus
- Exit

Tobt euch auch, bleibt aber bitte realistisch.

--------------------------------------------------

Als Übersicht welche Settings bis Jetzt geplant wären und wie der stand ist:

- [ ] Lautstärke (Auch einzelne Komponenten wie Musik usw.)
- [ ] Vollbild an/aus
- [ ] Exit-Button
- [ ] Zurück Button (zur Map)
- [ ] Auflösung
- [ ] Secret Buttons (mal schauen was  alles, darf auch gerne Vorschläge gemacht werden wenn jemand Lust hat)

**Comment by weirdmustard** [comment]
Musik an/aus würde ich noch reinnehmen neben Lautstärke

**Comment by Pandaoria** [comment]
Closed
