### ISSUE TITLE
MapView <-> CombatView - Mehrere Issues

### ISSUE THREAD

**Issue by weirdmustard** [L2P-Academy/FIAE1_RPG#174]
Ich hab jetzt den halben Nachmittag damit verbracht, zu versuchen, der CombatView ein anderes Hintergrundbild als das alte Forest01.jpg zu geben und dachte, wo ist das denn, nirgends im CombatView spricht es an, welcher Hintergrund verwendet werden soll. Versucht über die "battleLocation" aus nem neu angelegten Ordner zu ziehen - nix. Als ich alles frustriert wieder rückgängig gemacht hatte, hab ich die Forest01.jpg doch noch gefunden - im MapView. 

Aktuell ist es also so, dass der Klick auf "Kämpfen" auslöst, dass ein neuer View mit der Forest01.jpg geladen wird, nicht die CombatView selbst. Danach nutzt es allerdings die statischen Enemy und Kampfwerte aus der CombatView, die nur für diesen einen Beispielkampf gelten.

Oder sollte das so und ich versteh irgendwas nicht?

Also die BattleBackground Vorschläge liegen (nach push) nun unter img/BattleBackgrounds/location (zB "forest"). Das kann _man_ dann über "battleLocation" im CombatView zuweisen und bei Event auslösen laden lassen.

**Comment by L2P-Academy** [comment]
Derzeit gibt es noch den Bug, dass die MapView sich mehrfach öffnet, wenn man vom Kampf zurückkehrt

**Comment by weirdmustard** [comment]
Uuuund den Doppelsound zwischen Map und Combat. Wenn Combat aufgeht, legt sich die Combat-Musik über die Map-Musik und bleibt auch da laufend wenn man Combat schließt.
