### ISSUE TITLE
Aufgabenverteilung: Wer macht was? 

### ISSUE THREAD

**Issue by weirdmustard** [L2P-Academy/FIAE1_RPG#19]
**Code ist verteilt, wer möchte welche Inhalte miterstellen?**

Text:

- Quests schreiben - Rakinos89
- Storyline schreiben
- NPC Lore 

Bilder:

- Hintergründe kreieren - Rida?
- Charaktermenü-Illustration anlegen
- Charakterbilder generieren - Weirdmustard
- Itembilder kreieren - Weirdmustard
- Enemybilder generieren - Weirdmustard

Sound:

- Sounds basteln - Hr. Bauch
- Hintergrundmusik auswählen - Hr. Bauch
- AI Vertonung der Questtexte - Rakinos89
- Helden dubben - Velsabor

Anderes? :

(Bitte Bescheid sagen, was in der Liste fehlt und was ihr machen wollt)

**Comment by weirdmustard** [comment]
Hab das noch mal geupdated und strukturiert. Wenn euch noch was einfällt beim Coden, sagt Bescheid. 

Meinen Illustrationsteil mach ich in Aseprite. Wenn ich paar hab, geb ich nen Ordner frei zum Schauen.

**Comment by Rakinos89** [comment]
Kannst mich eintragen für Quests schreiben und AI Vertonung der Questtexte. Falls da jemand mitmachen möchte wäre top :D

**Comment by Velsabor** [comment]
> Kannst mich eintragen für Quests schreiben und AI Vertonung der Questtexte. Falls da jemand mitmachen möchte wäre top :D

hatte vor die Helden zu Duben

**Comment by weirdmustard** [comment]
Hab euch drinne.
