### ISSUE TITLE
Ideen für GameSounds / SoundController.java

### ISSUE THREAD

**Issue by L2P-Academy** [L2P-Academy/FIAE1_RPG#20]
# GameSounds - Vorschläge

## Musik

- Startmenü-Musik (bereits vorhanden)
- Intro-Musik (bereits vorhanden)
- Combat-Musik (bereits vorhanden)
- Tavernen-Musik für Quests (bereits vorhanden)
- Dungeon-Musik (normal)
- Dungeon-Musik (Kampf)
- Boss-Kampf-Musik
- Trader-Musik
- Sieges-Musik
- Niederlagen-Musik
- Credit-Musik
- Close-To-Death-Music
- Map - Musik (allgemein)

## GameSounds (Events/Actions)

- Button-Click-Sounds
- Gold-Sound (Erhalten + Ausgeben extra)
- Progress steigt (z.B. Erfahrungsleiste)
- Inventar öffnen/schließen (Rucksack-Sound)
- Gegenstand reparieren
- Gegenstand zerbrochen
- Gegenstand ausrüsten / ablegen

## Fähigkeiten / Kampf

- Schwert-Schlag
- Bogen-Angriff
- Block/Schild
- Feuer, Wasser, Wind usw.
- Heilzauber & Heiltrank
- Boss-Sounds / Attacken

## Stimmen / NPC-Sounds

- Zwerg, Elf, Orc, Mensch - "Ruf"
- Quest angenommen / abgeschlossen
- Boss-Stimmen
- Spieler-Interaktion (Hallo, Danke, Nein Danke, Tschüss...)

## Ambient-Sounds

- Wetter (Sonne, Regen, Wind, Gewitter)
- Tag/Nacht
- Wald, Fluss, Dorf, Stadt, Lager(feuer), Berg/Gipfel
- Höhle (Tropfstein, Hall/Echo, Fledermaus)
- Kerker (Kettenrasseln, Gefängnistür)
- evtl. Festung, Arena etc.

**Comment by Pandaoria** [comment]
Hier einmal ein pa beispiele fürs Intro.
Alle Ki generiert (geht sehr einfach und ist kostenlos) und man kann alles runterladen.
Nur Musik:
- https://www.udio.com/songs/5Eme8xu4d7jrKidVzkh5eC
- https://www.udio.com/songs/mM5XesVBABBqi9kRD8KaRL

Mit Lyrics:
- https://www.udio.com/songs/gU9J9H6LXeHxW8Hfbo5VnT
- https://www.udio.com/songs/n8DBneTRWUKrKgQvaVjYjP

**Comment by Velsabor** [comment]
[https://www.udio.com/songs/hyLjUZvyQ2FcTyADsVSXeb](url)

**Comment by Velsabor** [comment]
https://www.udio.com/songs/sxvjQeMJiriY1N2sxm1FEN
