### ISSUE TITLE
SettingsView: Ist noch unvollständig, Lautstärkeregler

### ISSUE THREAD

**Issue by L2P-Academy** [L2P-Academy/FIAE1_RPG#226]

**Comment by L2P-Academy** [comment]
Anwenden-Button zum Aktualisieren, ggf. weitere Einstellungen

**Comment by L2P-Academy** [comment]
Bug: Extra-Fenster öffnet sich, wenn Vollbild geklickt wird

**Comment by Pandaoria** [comment]
Update:
- Anwenden Button existiert und muss nur noch mit allen Funktionen gefüllt werden
- Bug sollte gefixed sein

**Comment by Pandaoria** [comment]
TODO:
-QuitButton ändern zu CharacterView

**Comment by L2P-Academy** [comment]
Abgeschlossen :)
