### ISSUE TITLE
CombatController sucht ein neues Zuhause! 

### ISSUE THREAD

**Issue by L2P-Academy** [L2P-Academy/FIAE1_RPG#57]
Bisher bearbeitet niemand den CombatController, wer möchte einfach ein kleiner Hinweis und oben rechts assignen/zuweisen

**Comment by antcedric91** [comment]
Da ich mich bereit erklärt habe CombatView zu übernehmen, könnte ich versuchen teilweise auch CombatController zu machen, da beide viel miteinander arbeiten.

Aber ich habe keine Ahnung von View oder Controller, werde also versuchen mich langsam in der View und dann im Controller reinzuarbeiten..

**Comment by christian-gassmann** [comment]
Wenn ich mit dem XMLController fertig bin, könnte ich auch mit machen

**Comment by L2P-Academy** [comment]
Dann assignen Sie beide sich mal darauf, damit es dokumentiert ist :)
