### ISSUE TITLE
Quests - Ideen/vorschläge

### ISSUE THREAD

**Issue by Rakinos89** [L2P-Academy/FIAE1_RPG#87]
Hier ist bereits eine Liste mit 10 vorbereiteten Quests. Wenn ihr Änderungen vornehmen möchtet oder etwas hinzufügen oder entfernen möchtet, lass es mich bitte wissen, indem ihr kommentiert oder mir Bescheid gibt.

[Quest List.pdf](https://github.com/L2P-Academy/FIAE1_DnD/files/15272656/Quest.List.pdf)

**Comment by weirdmustard** [comment]
Mein NPC von neulich hat ne eigene Quest dabei, falls du die mit einbauen willst. https://github.com/weirdmustard/Hausaufgaben_fachmod/blob/master/src/hausauf_fachmod/Auf_260424.java

**Comment by Rakinos89** [comment]
Updated!
