### ISSUE TITLE
Map interaktiv machen -> testbereit für alle anderen Views

### ISSUE THREAD

**Issue by L2P-Academy** [L2P-Academy/FIAE1_RPG#98]
- die Map braucht einen Startpunkt (entweder interaktiv bzw. vom programm erzeugt - ODER: mehrere Bilder der Karte mit Markierungen)
- es müssen Elemente auf der Map anklickbar sein, um neue Quests bzw. Kämpfe zu starten
- Buttons zum Testen (temporär) für: SavegameView, CombatView, JournalView (derzeit QuestView), CreditView, ggf. abstimmen mit den anderen Teilnehmern

**Comment by L2P-Academy** [comment]
@MaximilianGietz Keine Sorge, entweder machen wir das im nächsten Kurs, wo es um Animation und Anpassung von Views geht, oder wir schaffen das noch nach der Klausur. Die interaktive Map ist tatsächlich ziemlich schwierig, ich würde das dann gemeinsam als Code-Demo mit Ihnen machen wollen.

**Comment by weirdmustard** [comment]
Ich guck mir die Map noch mal an übers Wochenende und hoffe, Montag was sinnvoll weitentwickeltes vorzeigen zu können.
